spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

  # https://www.e4developer.com/2018/01/28/setting-up-rabbitmq-with-spring-cloud-stream/
  # spring.cloud.stream.bindings.<channel-name>.destination
  cloud:
    stream:
      bindings:
        input:
          destination: no-mouth-found-exchange
          group: nose-find-group
        noseFoundChannel:
          destination: nose-found-exchange
        noNoseFoundChannel:
          destination: no-nose-found-exchange
server:
  port: 8083

application:
  classifier:
    file:
