version: '2'
services:
  proxy:
    image: foxylion/nginx-self-signed-https:latest
    environment:
      - "REMOTE_URL=http://image-uploader-app:8080"
    ports:
      - 9000:80
      - 9443:443
  image-uploader-app:
    image: hftm/image-uploader:latest
    environment:
      - "SPRING_RABBITMQ_HOST=rabbit-mq"
      - "SPRING_RABBITMQ_USERNAME=admin"
      - "SPRING_RABBITMQ_PASSWORD=admin"
    # ports:
    #   - 8080:8080
    #   - 8180:8180
  face-finder-app:
    image: hftm/face-finder:latest
    environment:
      - "SPRING_RABBITMQ_HOST=rabbit-mq"
      - "SPRING_RABBITMQ_USERNAME=admin"
      - "SPRING_RABBITMQ_PASSWORD=admin"
    # ports:
    #   - 8081:8081
    #   - 8181:8181
  mouth-finder-app:
    image: hftm/mouth-finder:latest
    environment:
      - "SPRING_RABBITMQ_HOST=rabbit-mq"
      - "SPRING_RABBITMQ_USERNAME=admin"
      - "SPRING_RABBITMQ_PASSWORD=admin"
    # ports:
    #   - 8082:8082
    #   - 8282:8282
  nose-finder-app:
    image: hftm/nose-finder:latest
    environment:
      - "SPRING_RABBITMQ_HOST=rabbit-mq"
      - "SPRING_RABBITMQ_USERNAME=admin"
      - "SPRING_RABBITMQ_PASSWORD=admin"
    # ports:
    #   - 8083:8083
    #   - 8383:8383
  mask-detection-notifier-app:
    image: hftm/mask-detection-notifier:latest
    environment:
      - "SPRING_RABBITMQ_HOST=rabbit-mq"
      - "SPRING_RABBITMQ_USERNAME=admin"
      - "SPRING_RABBITMQ_PASSWORD=admin"
      - "SPRING_MAIL_HOST=mailcatcher"
      - "SPRING_MAIL_PORT=1025"
    # ports:
    #   - 8084:8084
    #   - 8484:8484

  rabbit-mq:
    image: rabbitmq:3-management
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin"
    ports:
      - 15672:15672
      - 5672:5672
  
  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
      - 1080:1080
      - 1025:1025
